// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activate_version.sql

package sqlcgen

import (
	"context"
)

const activateVersion = `-- name: ActivateVersion :exec
UPDATE ingest.mrf_files
SET is_active = true, status = 'active'
WHERE mrf_file_id = $1
`

func (q *Queries) ActivateVersion(ctx context.Context, mrfFileID int64) error {
	_, err := q.db.Exec(ctx, activateVersion, mrfFileID)
	return err
}
