// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyze_staging.sql

package sqlcgen

import (
	"context"
)

const analyzeStaging = `-- name: AnalyzeStaging :exec
ANALYZE ingest.stage_charge_rows
`

func (q *Queries) AnalyzeStaging(ctx context.Context) error {
	_, err := q.db.Exec(ctx, analyzeStaging)
	return err
}
