// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyze_prices.sql

package sqlcgen

import (
	"context"
)

const analyzePrices = `-- name: AnalyzePrices :exec
ANALYZE mrf.prices_by_code
`

func (q *Queries) AnalyzePrices(ctx context.Context) error {
	_, err := q.db.Exec(ctx, analyzePrices)
	return err
}
