// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deactivate_older_versions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deactivateOlderVersions = `-- name: DeactivateOlderVersions :execresult
UPDATE ingest.mrf_files
SET is_active = false
WHERE hospital_id = $1
  AND mrf_file_id <> $2
  AND is_active = true
`

type DeactivateOlderVersionsParams struct {
	HospitalID int64
	MrfFileID  int64
}

func (q *Queries) DeactivateOlderVersions(ctx context.Context, arg DeactivateOlderVersionsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deactivateOlderVersions, arg.HospitalID, arg.MrfFileID)
}
