// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_staging_by_file.sql

package sqlcgen

import (
	"context"
)

const deleteStagingByFile = `-- name: DeleteStagingByFile :exec
DELETE FROM ingest.stage_charge_rows WHERE mrf_file_id = $1
`

func (q *Queries) DeleteStagingByFile(ctx context.Context, mrfFileID int64) error {
	_, err := q.db.Exec(ctx, deleteStagingByFile, mrfFileID)
	return err
}
