// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_serving_by_file.sql

package sqlcgen

import (
	"context"
)

const deleteServingByFile = `-- name: DeleteServingByFile :exec
DELETE FROM mrf.prices_by_code WHERE mrf_file_id = $1
`

func (q *Queries) DeleteServingByFile(ctx context.Context, mrfFileID int64) error {
	_, err := q.db.Exec(ctx, deleteServingByFile, mrfFileID)
	return err
}
