// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_staging_batch.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const deleteStagingBatch = `-- name: DeleteStagingBatch :execresult
DELETE FROM ingest.stage_charge_rows
WHERE ingest_batch_id = $1
`

func (q *Queries) DeleteStagingBatch(ctx context.Context, ingestBatchID uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteStagingBatch, ingestBatchID)
}
