// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookup_mrf_file.sql

package sqlcgen

import (
	"context"
)

const lookupMRFFile = `-- name: LookupMRFFile :one
SELECT mrf_file_id, status FROM ingest.mrf_files
WHERE hospital_id = $1
  AND source_file_sha256 = $2
`

type LookupMRFFileParams struct {
	HospitalID       int64
	SourceFileSha256 string
}

type LookupMRFFileRow struct {
	MrfFileID int64
	Status    string
}

func (q *Queries) LookupMRFFile(ctx context.Context, arg LookupMRFFileParams) (*LookupMRFFileRow, error) {
	row := q.db.QueryRow(ctx, lookupMRFFile, arg.HospitalID, arg.SourceFileSha256)
	var i LookupMRFFileRow
	err := row.Scan(&i.MrfFileID, &i.Status)
	return &i, err
}
