// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookup_hospital_by_name.sql

package sqlcgen

import (
	"context"
)

const lookupHospitalByName = `-- name: LookupHospitalByName :one
SELECT hospital_id FROM ref.hospitals WHERE hospital_name = $1 LIMIT 1
`

func (q *Queries) LookupHospitalByName(ctx context.Context, hospitalName string) (int64, error) {
	row := q.db.QueryRow(ctx, lookupHospitalByName, hospitalName)
	var hospital_id int64
	err := row.Scan(&hospital_id)
	return hospital_id, err
}
