// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IngestMrfFile struct {
	MrfFileID        int64
	HospitalID       int64
	SourceFileName   string
	SourceFileSha256 string
	Version          *string
	LastUpdatedOn    *time.Time
	Affirmation      *bool
	FileSizeBytes    *int64
	Status           string
	ImportedAt       pgtype.Timestamptz
	IsActive         bool
}

type IngestStageChargeRow struct {
	IngestBatchID           uuid.UUID
	MrfFileID               int64
	SourceRowNumber         int64
	SourceRowHash           []byte
	HospitalName            *string
	HospitalLocation        *string
	HospitalAddress         *string
	LicenseNumber           *string
	LicenseState            *string
	Version                 *string
	LastUpdatedOn           *time.Time
	Affirmation             *bool
	Description             string
	Setting                 *string
	BillingClass            *string
	CptCode                 *string
	HcpcsCode               *string
	MsDrgCode               *string
	NdcCode                 *string
	CdtCode                 *string
	PayerName               *string
	PayerNameNorm           *string
	PlanName                *string
	PlanNameNorm            *string
	GrossChargeCents        *int64
	DiscountedCashCents     *int64
	NegotiatedDollarCents   *int64
	NegotiatedPercentageBps *int32
	EstimatedAmountCents    *int64
	MinChargeCents          *int64
	MaxChargeCents          *int64
	Methodology             *string
	NegotiatedAlgorithm     *string
	DrugUnit                *string
	DrugUnitType            *string
	Modifiers               *string
	AdditionalGenericNotes  *string
	AdditionalPayerNotes    *string
}

type MrfPricesByCode struct {
	PriceRowID              int64
	MrfFileID               int64
	HospitalID              int64
	CodeType                string
	CodeRaw                 string
	CodeNorm                string
	Description             string
	Setting                 *string
	BillingClass            *string
	PayerID                 *int64
	PlanID                  *int64
	PayerNameRaw            *string
	PlanNameRaw             *string
	GrossChargeCents        *int64
	DiscountedCashCents     *int64
	NegotiatedDollarCents   *int64
	NegotiatedPercentageBps *int32
	EstimatedAmountCents    *int64
	MinChargeCents          *int64
	MaxChargeCents          *int64
	Methodology             *string
	NegotiatedAlgorithm     *string
	DrugUnit                *string
	DrugUnitType            *string
	Modifiers               *string
	AdditionalGenericNotes  *string
	AdditionalPayerNotes    *string
	SourceRowHash           []byte
	ImportedAt              pgtype.Timestamptz
}

type MrfPricesByCodeCdt struct {
	PriceRowID              int64
	MrfFileID               int64
	HospitalID              int64
	CodeType                string
	CodeRaw                 string
	CodeNorm                string
	Description             string
	Setting                 *string
	BillingClass            *string
	PayerID                 *int64
	PlanID                  *int64
	PayerNameRaw            *string
	PlanNameRaw             *string
	GrossChargeCents        *int64
	DiscountedCashCents     *int64
	NegotiatedDollarCents   *int64
	NegotiatedPercentageBps *int32
	EstimatedAmountCents    *int64
	MinChargeCents          *int64
	MaxChargeCents          *int64
	Methodology             *string
	NegotiatedAlgorithm     *string
	DrugUnit                *string
	DrugUnitType            *string
	Modifiers               *string
	AdditionalGenericNotes  *string
	AdditionalPayerNotes    *string
	SourceRowHash           []byte
	ImportedAt              pgtype.Timestamptz
}

type MrfPricesByCodeCpt struct {
	PriceRowID              int64
	MrfFileID               int64
	HospitalID              int64
	CodeType                string
	CodeRaw                 string
	CodeNorm                string
	Description             string
	Setting                 *string
	BillingClass            *string
	PayerID                 *int64
	PlanID                  *int64
	PayerNameRaw            *string
	PlanNameRaw             *string
	GrossChargeCents        *int64
	DiscountedCashCents     *int64
	NegotiatedDollarCents   *int64
	NegotiatedPercentageBps *int32
	EstimatedAmountCents    *int64
	MinChargeCents          *int64
	MaxChargeCents          *int64
	Methodology             *string
	NegotiatedAlgorithm     *string
	DrugUnit                *string
	DrugUnitType            *string
	Modifiers               *string
	AdditionalGenericNotes  *string
	AdditionalPayerNotes    *string
	SourceRowHash           []byte
	ImportedAt              pgtype.Timestamptz
}

type MrfPricesByCodeHcpc struct {
	PriceRowID              int64
	MrfFileID               int64
	HospitalID              int64
	CodeType                string
	CodeRaw                 string
	CodeNorm                string
	Description             string
	Setting                 *string
	BillingClass            *string
	PayerID                 *int64
	PlanID                  *int64
	PayerNameRaw            *string
	PlanNameRaw             *string
	GrossChargeCents        *int64
	DiscountedCashCents     *int64
	NegotiatedDollarCents   *int64
	NegotiatedPercentageBps *int32
	EstimatedAmountCents    *int64
	MinChargeCents          *int64
	MaxChargeCents          *int64
	Methodology             *string
	NegotiatedAlgorithm     *string
	DrugUnit                *string
	DrugUnitType            *string
	Modifiers               *string
	AdditionalGenericNotes  *string
	AdditionalPayerNotes    *string
	SourceRowHash           []byte
	ImportedAt              pgtype.Timestamptz
}

type MrfPricesByCodeMsDrg struct {
	PriceRowID              int64
	MrfFileID               int64
	HospitalID              int64
	CodeType                string
	CodeRaw                 string
	CodeNorm                string
	Description             string
	Setting                 *string
	BillingClass            *string
	PayerID                 *int64
	PlanID                  *int64
	PayerNameRaw            *string
	PlanNameRaw             *string
	GrossChargeCents        *int64
	DiscountedCashCents     *int64
	NegotiatedDollarCents   *int64
	NegotiatedPercentageBps *int32
	EstimatedAmountCents    *int64
	MinChargeCents          *int64
	MaxChargeCents          *int64
	Methodology             *string
	NegotiatedAlgorithm     *string
	DrugUnit                *string
	DrugUnitType            *string
	Modifiers               *string
	AdditionalGenericNotes  *string
	AdditionalPayerNotes    *string
	SourceRowHash           []byte
	ImportedAt              pgtype.Timestamptz
}

type MrfPricesByCodeNdc struct {
	PriceRowID              int64
	MrfFileID               int64
	HospitalID              int64
	CodeType                string
	CodeRaw                 string
	CodeNorm                string
	Description             string
	Setting                 *string
	BillingClass            *string
	PayerID                 *int64
	PlanID                  *int64
	PayerNameRaw            *string
	PlanNameRaw             *string
	GrossChargeCents        *int64
	DiscountedCashCents     *int64
	NegotiatedDollarCents   *int64
	NegotiatedPercentageBps *int32
	EstimatedAmountCents    *int64
	MinChargeCents          *int64
	MaxChargeCents          *int64
	Methodology             *string
	NegotiatedAlgorithm     *string
	DrugUnit                *string
	DrugUnitType            *string
	Modifiers               *string
	AdditionalGenericNotes  *string
	AdditionalPayerNotes    *string
	SourceRowHash           []byte
	ImportedAt              pgtype.Timestamptz
}

type RefHospital struct {
	HospitalID       int64
	HospitalName     string
	HospitalLocation *string
	HospitalAddress  *string
	LicenseNumber    *string
	LicenseState     *string
	NpiList          []string
	CreatedAt        pgtype.Timestamptz
}

type RefPayer struct {
	PayerID       int64
	PayerName     string
	PayerNameNorm string
}

type RefPlan struct {
	PlanID       int64
	PayerID      *int64
	PlanName     string
	PlanNameNorm string
}
