// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: register_mrf_file.sql

package sqlcgen

import (
	"context"
	"time"
)

const registerMRFFile = `-- name: RegisterMRFFile :one
INSERT INTO ingest.mrf_files (hospital_id, source_file_name, source_file_sha256, version, last_updated_on, affirmation, file_size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (hospital_id, source_file_sha256) DO NOTHING
RETURNING mrf_file_id, status
`

type RegisterMRFFileParams struct {
	HospitalID       int64
	SourceFileName   string
	SourceFileSha256 string
	Version          *string
	LastUpdatedOn    *time.Time
	Affirmation      *bool
	FileSizeBytes    *int64
}

type RegisterMRFFileRow struct {
	MrfFileID int64
	Status    string
}

func (q *Queries) RegisterMRFFile(ctx context.Context, arg RegisterMRFFileParams) (*RegisterMRFFileRow, error) {
	row := q.db.QueryRow(ctx, registerMRFFile,
		arg.HospitalID,
		arg.SourceFileName,
		arg.SourceFileSha256,
		arg.Version,
		arg.LastUpdatedOn,
		arg.Affirmation,
		arg.FileSizeBytes,
	)
	var i RegisterMRFFileRow
	err := row.Scan(&i.MrfFileID, &i.Status)
	return &i, err
}
