// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resolve_hospital.sql

package sqlcgen

import (
	"context"
)

const resolveHospital = `-- name: ResolveHospital :one
INSERT INTO ref.hospitals (hospital_name, hospital_location, hospital_address, license_number, license_state)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING hospital_id
`

type ResolveHospitalParams struct {
	HospitalName     string
	HospitalLocation *string
	HospitalAddress  *string
	LicenseNumber    *string
	LicenseState     *string
}

func (q *Queries) ResolveHospital(ctx context.Context, arg ResolveHospitalParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveHospital,
		arg.HospitalName,
		arg.HospitalLocation,
		arg.HospitalAddress,
		arg.LicenseNumber,
		arg.LicenseState,
	)
	var hospital_id int64
	err := row.Scan(&hospital_id)
	return hospital_id, err
}
