// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_mrf_status.sql

package sqlcgen

import (
	"context"
)

const updateMRFStatus = `-- name: UpdateMRFStatus :exec
UPDATE ingest.mrf_files
SET status = $1
WHERE mrf_file_id = $2
`

type UpdateMRFStatusParams struct {
	Status    string
	MrfFileID int64
}

func (q *Queries) UpdateMRFStatus(ctx context.Context, arg UpdateMRFStatusParams) error {
	_, err := q.db.Exec(ctx, updateMRFStatus, arg.Status, arg.MrfFileID)
	return err
}
