// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upsert_plans.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const upsertPlans = `-- name: UpsertPlans :execresult
INSERT INTO ref.plans (payer_id, plan_name, plan_name_norm)
SELECT DISTINCT p.payer_id, s.plan_name, s.plan_name_norm
FROM ingest.stage_charge_rows s
JOIN ref.payers p ON p.payer_name_norm = s.payer_name_norm
WHERE s.ingest_batch_id = $1
  AND s.plan_name_norm IS NOT NULL
ON CONFLICT (payer_id, plan_name_norm) DO NOTHING
`

func (q *Queries) UpsertPlans(ctx context.Context, ingestBatchID uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertPlans, ingestBatchID)
}
