// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upsert_payers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const upsertPayers = `-- name: UpsertPayers :execresult
INSERT INTO ref.payers (payer_name, payer_name_norm)
SELECT DISTINCT s.payer_name, s.payer_name_norm
FROM ingest.stage_charge_rows s
WHERE s.ingest_batch_id = $1
  AND s.payer_name_norm IS NOT NULL
ON CONFLICT (payer_name_norm) DO NOTHING
`

func (q *Queries) UpsertPayers(ctx context.Context, ingestBatchID uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertPayers, ingestBatchID)
}
